name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.6.2] # Adjust Node.js versions as needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Lint code
      run: npm run lint # Make sure you have a lint script in package.json

    - name: Build project
      run: npm run build # Make sure you have a build script in package.json

    - name: Upload coverage report
      if: success() && steps.test.outcome == 'success'
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: ./coverage # Adjust path if needed
